/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCatalogoRouteImport } from './routes/_authenticated/catalogo'
import { Route as AuthenticatedCompararRouteImport } from './routes/_authenticated/comparar'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAuditoriaRouteImport } from './routes/_authenticated/admin.auditoria'
import { Route as AuthenticatedAdminCategoriasRouteImport } from './routes/_authenticated/admin.categorias'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin.configuracoes'
import { Route as AuthenticatedAdminHistoricoRouteImport } from './routes/_authenticated/admin.historico'
import { Route as AuthenticatedAdminMarcasRouteImport } from './routes/_authenticated/admin.marcas'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedMaquinaIdRouteImport } from './routes/_authenticated/maquina.$id'
import { Route as AuthenticatedAdminMaquinasIndexRouteImport } from './routes/_authenticated/admin.maquinas.index'
import { Route as AuthenticatedAdminMaquinasIdRouteImport } from './routes/_authenticated/admin.maquinas.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatalogoRoute = AuthenticatedCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompararRoute = AuthenticatedCompararRouteImport.update({
  id: '/comparar',
  path: '/comparar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAuditoriaRoute =
  AuthenticatedAdminAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriasRoute =
  AuthenticatedAdminCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHistoricoRoute =
  AuthenticatedAdminHistoricoRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarcasRoute =
  AuthenticatedAdminMarcasRouteImport.update({
    id: '/marcas',
    path: '/marcas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedMaquinaIdRoute = AuthenticatedMaquinaIdRouteImport.update({
  id: '/maquina/$id',
  path: '/maquina/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminMaquinasIndexRoute =
  AuthenticatedAdminMaquinasIndexRouteImport.update({
    id: '/maquinas/',
    path: '/maquinas/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMaquinasIdRoute =
  AuthenticatedAdminMaquinasIdRouteImport.update({
    id: '/maquinas/$id',
    path: '/maquinas/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/catalogo': typeof AuthenticatedCatalogoRoute
  '/comparar': typeof AuthenticatedCompararRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/historico': typeof AuthenticatedAdminHistoricoRoute
  '/admin/marcas': typeof AuthenticatedAdminMarcasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/maquina/$id': typeof AuthenticatedMaquinaIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/maquinas/$id': typeof AuthenticatedAdminMaquinasIdRoute
  '/admin/maquinas/': typeof AuthenticatedAdminMaquinasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/catalogo': typeof AuthenticatedCatalogoRoute
  '/comparar': typeof AuthenticatedCompararRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/historico': typeof AuthenticatedAdminHistoricoRoute
  '/admin/marcas': typeof AuthenticatedAdminMarcasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/maquina/$id': typeof AuthenticatedMaquinaIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/maquinas/$id': typeof AuthenticatedAdminMaquinasIdRoute
  '/admin/maquinas': typeof AuthenticatedAdminMaquinasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/catalogo': typeof AuthenticatedCatalogoRoute
  '/_authenticated/comparar': typeof AuthenticatedCompararRoute
  '/_authenticated/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/_authenticated/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/historico': typeof AuthenticatedAdminHistoricoRoute
  '/_authenticated/admin/marcas': typeof AuthenticatedAdminMarcasRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/maquina/$id': typeof AuthenticatedMaquinaIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/maquinas/$id': typeof AuthenticatedAdminMaquinasIdRoute
  '/_authenticated/admin/maquinas/': typeof AuthenticatedAdminMaquinasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/catalogo'
    | '/comparar'
    | '/admin/auditoria'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/historico'
    | '/admin/marcas'
    | '/admin/usuarios'
    | '/maquina/$id'
    | '/admin/'
    | '/admin/maquinas/$id'
    | '/admin/maquinas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/catalogo'
    | '/comparar'
    | '/admin/auditoria'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/historico'
    | '/admin/marcas'
    | '/admin/usuarios'
    | '/maquina/$id'
    | '/admin'
    | '/admin/maquinas/$id'
    | '/admin/maquinas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/catalogo'
    | '/_authenticated/comparar'
    | '/_authenticated/admin/auditoria'
    | '/_authenticated/admin/categorias'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/historico'
    | '/_authenticated/admin/marcas'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/maquina/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/maquinas/$id'
    | '/_authenticated/admin/maquinas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalogo': {
      id: '/_authenticated/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof AuthenticatedCatalogoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comparar': {
      id: '/_authenticated/comparar'
      path: '/comparar'
      fullPath: '/comparar'
      preLoaderRoute: typeof AuthenticatedCompararRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/auditoria': {
      id: '/_authenticated/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categorias': {
      id: '/_authenticated/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/historico': {
      id: '/_authenticated/admin/historico'
      path: '/historico'
      fullPath: '/admin/historico'
      preLoaderRoute: typeof AuthenticatedAdminHistoricoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/marcas': {
      id: '/_authenticated/admin/marcas'
      path: '/marcas'
      fullPath: '/admin/marcas'
      preLoaderRoute: typeof AuthenticatedAdminMarcasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/maquina/$id': {
      id: '/_authenticated/maquina/$id'
      path: '/maquina/$id'
      fullPath: '/maquina/$id'
      preLoaderRoute: typeof AuthenticatedMaquinaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/maquinas/': {
      id: '/_authenticated/admin/maquinas/'
      path: '/maquinas'
      fullPath: '/admin/maquinas/'
      preLoaderRoute: typeof AuthenticatedAdminMaquinasIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/maquinas/$id': {
      id: '/_authenticated/admin/maquinas/$id'
      path: '/maquinas/$id'
      fullPath: '/admin/maquinas/$id'
      preLoaderRoute: typeof AuthenticatedAdminMaquinasIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditoriaRoute: typeof AuthenticatedAdminAuditoriaRoute
  AuthenticatedAdminCategoriasRoute: typeof AuthenticatedAdminCategoriasRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminHistoricoRoute: typeof AuthenticatedAdminHistoricoRoute
  AuthenticatedAdminMarcasRoute: typeof AuthenticatedAdminMarcasRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminMaquinasIdRoute: typeof AuthenticatedAdminMaquinasIdRoute
  AuthenticatedAdminMaquinasIndexRoute: typeof AuthenticatedAdminMaquinasIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditoriaRoute: AuthenticatedAdminAuditoriaRoute,
  AuthenticatedAdminCategoriasRoute: AuthenticatedAdminCategoriasRoute,
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminHistoricoRoute: AuthenticatedAdminHistoricoRoute,
  AuthenticatedAdminMarcasRoute: AuthenticatedAdminMarcasRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminMaquinasIdRoute: AuthenticatedAdminMaquinasIdRoute,
  AuthenticatedAdminMaquinasIndexRoute: AuthenticatedAdminMaquinasIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCatalogoRoute: typeof AuthenticatedCatalogoRoute
  AuthenticatedCompararRoute: typeof AuthenticatedCompararRoute
  AuthenticatedMaquinaIdRoute: typeof AuthenticatedMaquinaIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCatalogoRoute: AuthenticatedCatalogoRoute,
  AuthenticatedCompararRoute: AuthenticatedCompararRoute,
  AuthenticatedMaquinaIdRoute: AuthenticatedMaquinaIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
