// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// NOTA: brokeredPreviewStorage REMOVIDO intencionalmente do build de
// produção. Em hospedagem compartilhada fora do domínio Lovable, o broker
// de sessão via window.parent.postMessage() não tem ninguém do outro lado
// para responder — então cada `getItem` pendura 2s + retry 250ms e, em
// focos repetidos no input (auth), causa fila gigante de timeouts →
// event loop trava → Chrome mostra "Página sem resposta". Em produção /
// build estático (SPA cliente), usamos APENAS localStorage padrão do
// Supabase (igual qualquer app React normal).
//
// Se você precisar de preview sincronizado no editor Lovable, use o build
// `npm run dev` com wrapper oficial (create-supabase-client original).

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

let _initError: Error | null = null;

function createSupabaseClient() {
  if (_initError) return null;

  // 🔑 CRÍTICO: Vite (build-time) SÓ substitui `import.meta.env.VITE_ALGUMA_COISA
  // acessados DIRETAMENTE, sem optional chaining / casts as any / desestruturação.
  // Se usarmos (import.meta as any)?.env o Vite NÃO FAZ a substituição e o
  // valor fica undefined no bundle de produção, caindo no stub warning "Missing
  // Supabase vars". Abaixo acessamos cada variável diretamente e também
  // garantimos que o build enxerga.
  const VITE_URL = (import.meta.env.VITE_SUPABASE_URL as string | undefined) ?? undefined;
  const VITE_ANON = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined) ?? undefined;

  const WINDOW_ENV =
    typeof window !== 'undefined'
      ? (window as any).__VITE_ENV__ ||
        (() => {
          const metaUrl = document.querySelector<HTMLMetaElement>('meta[name="env:VITE_SUPABASE_URL"]')?.content;
          const metaAnon = document.querySelector<HTMLMetaElement>('meta[name="env:VITE_SUPABASE_PUBLISHABLE_KEY"]')?.content;
          return {
            VITE_SUPABASE_URL: metaUrl || undefined,
            VITE_SUPABASE_PUBLISHABLE_KEY: metaAnon || undefined,
          };
        })()
      : {};

  const PROCESS_ENV = (() => {
    try {
      // fallback runtime: SSR edge node:browser não temos process (ou pode ser undefined
      // em strict mode). NOTA: Rolldown (Vite 8) não tolera ternários com ?? e
      // cast `as` no mesmo termo; vamos usar múltiplos ifs.
      let pEnv: Record<string, string | undefined> = {};
      if (typeof process !== 'undefined') {
        const procAny = process as any;
        if (procAny && procAny.env && typeof procAny.env === 'object') {
          pEnv = procAny.env;
        }
      }
      return {
        VITE_SUPABASE_URL: pEnv.VITE_SUPABASE_URL,
        VITE_SUPABASE_PUBLISHABLE_KEY: pEnv.VITE_SUPABASE_PUBLISHABLE_KEY,
        SUPABASE_URL: pEnv.SUPABASE_URL,
        SUPABASE_PUBLISHABLE_KEY: pEnv.SUPABASE_PUBLISHABLE_KEY,
      };
    } catch {
      return {} as any;
    }
  })();

  const SUPABASE_URL =
    VITE_URL ||
    WINDOW_ENV.VITE_SUPABASE_URL ||
    PROCESS_ENV.VITE_SUPABASE_URL ||
    PROCESS_ENV.SUPABASE_URL;

  const SUPABASE_PUBLISHABLE_KEY =
    VITE_ANON ||
    WINDOW_ENV.VITE_SUPABASE_PUBLISHABLE_KEY ||
    PROCESS_ENV.VITE_SUPABASE_PUBLISHABLE_KEY ||
    PROCESS_ENV.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}.`;
    if (typeof console !== 'undefined' && !_initError) {
      _initError = new Error(message);
      // eslint-disable-next-line no-console
      console.warn('[Supabase] ' + message + ' Login fica desabilitado. Verifique GitHub Secrets (VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY).');
    }
    return null;
  }

  try {
    return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      global: {
        fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
      },
      auth: {
        storage:
          typeof window !== 'undefined' && 'localStorage' in window
            ? {
                getItem: (key: string): string | null => {
                  try {
                    return localStorage.getItem(key);
                  } catch (err) {
                    return null;
                  }
                },
                setItem: (key: string, value: string): void => {
                  try {
                    localStorage.setItem(key, value);
                  } catch (_err) {
                    /* quota excedida / private mode: silencioso */
                  }
                },
                removeItem: (key: string): void => {
                  try {
                    localStorage.removeItem(key);
                  } catch (_err) {
                    /* noop */
                  }
                },
              }
            : undefined,
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
      }
    });
  } catch (e) {
    _initError = e instanceof Error ? e : new Error(String(e));
    // eslint-disable-next-line no-console
    console.error('[Supabase] createClient falhou:', _initError);
    return null;
  }
}

let _supabase: ReturnType<typeof createSupabaseClient>;

function createNullSupabase(): any {
  const noop = () => Promise.resolve({ data: null, error: new Error('Supabase not initialized') });
  return new Proxy(
    {
      auth: {
        getSession: () => Promise.resolve({ data: { session: null }, error: null }),
        getUser: () => Promise.resolve({ data: { user: null }, error: null }),
        signInWithPassword: noop,
        signUp: noop,
        signOut: () => Promise.resolve({ error: null }),
        onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
      },
      storage: { from: () => ({ upload: noop, remove: noop, list: noop, getPublicUrl: () => ({ data: { publicUrl: '' } }) }) },
      from: () => ({ select: () => ({ eq: () => ({ single: noop, maybeSingle: noop, order: () => ({ range: noop }), range: noop }), range: noop, order: () => ({ eq: noop }), single: noop, maybeSingle: noop, insert: noop, update: noop, delete: noop }) }),
      rpc: noop,
    },
    {
      get(t: any, p: string | symbol, r: any) {
        if (p in t) return Reflect.get(t, p, r);
        return () => Promise.resolve({ data: null, error: new Error('Supabase não inicializado') });
      },
    },
  );
}

// Inicializa UMA vez no carregamento do módulo. Sem Proxy externo.
// As variáveis de ambiente são lidas no createSupabaseClient(); se faltar,
// cai no createNullSupabase() (stub seguro) e loga warning UMA vez.
(function init() {
  try {
    const client = createSupabaseClient();
    _supabase = (client ?? (createNullSupabase() as any));
  } catch {
    _supabase = createNullSupabase() as any;
  }
})();

export const supabase = _supabase as ReturnType<typeof createClient<Database>>;

